'use client';

import Image from 'next/image'
import styles from './page.module.css'
import Head from 'next/head';
import AOS from 'aos';
import { useState, useEffect } from 'react';
import "aos/dist/aos.css"

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import { faDiscord } from '@fortawesome/free-brands-svg-icons';

export default function Home() {
  useEffect(() => {
    AOS.init();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={'text-3xl'}>Hello, World👋</h1>
        <img className={'pt-4'} src="https://lanyard.cnrad.dev/api/909235850922037329"></img>
      </main>

      <div className={'flex flex-col bg-zinc-900'}>
        <h1 className={'text-center text-2xl'}>About</h1>

        <div className={'mx-auto w-[95%] bg-[#36393e] rounded my-4 p-4'} data-aos="fade-up">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, praesentium.</p>
        </div>

        {/* <hr className="my-8 border-gray-400 dark:border-gray-500"></hr> */}

        <h1 className={'text-center text-2xl'}>Social media</h1>
        <div className={'mx-auto w-[95%] bg-[#36393e] rounded my-4 p-4'} data-aos="fade-up">
        <p className={'text-center'}><FontAwesomeIcon icon={faDiscord} /> Discord: <a href="https://discord.com/users/909235850922037329" className={'underline underline-offset-4'}>Eiotry#7958</a></p>
        </div>
        
      </div>

      <footer className={'bg-zinc-800 text-center py-4'}>
        <p>Made by <a href="https://github.com/zeor154/hello">Zeor154</a></p>
      </footer>

    </div>
  )
}
